CREATE DATABASE QLSach
ON PRIMARY
(NAME = QLSach_data, FILENAME = 'D:\CSDL\QLSach_Data.mdf',
SIZE = 20MB, MAXSIZE = 40MB, FILEGROWTH = 1MB)
LOG ON
	(NAME = QLSach_Log, FILENAME = 'D:\CSDL\QLSach_Log.ldf',
	SIZE = 6MB, MAXSIZE= 8MB, FILEGROWTH = 1MB);
ALTER DATABASE QLSach ADD FILEGROUP DuLieuSach
ALTER DATABASE QLSach
ADD FILE (NAME = QLSach_Data2, FILENAME = 'D:\CSDL\QLSach_Data2.ndf',
SIZE = 20MB, MAXSIZE = 40MB, FILEGROWTH = 1MB)
TO FILEGROUP DuLieuSach
ALTER DATABASE QLSach SET Read_Only
ALTER DATABASE QLSach SET Read_Write
ALTER AUTHORIZATION ON DATABASE::QLSach TO TT;