CREATE DATABASE QLSV;
GO
USE QLSV;
GO
CREATE TABLE LOP (
    MaLop CHAR(5) PRIMARY KEY NOT NULL,
    TenLop NVARCHAR(20) NOT NULL,
    SiSoDuKien INT,
    NgayKhaiGiang DATETIME
);

CREATE TABLE SINHVIEN (
    MaSV CHAR(5) PRIMARY KEY NOT NULL,
    TenHo NVARCHAR(40) NOT NULL,
    NgaySinh DATETIME NOT NULL,
    MaLop CHAR(5) NOT NULL,
    FOREIGN KEY (MaLop) REFERENCES LOP(MaLop)
);

CREATE TABLE MONHOC (
    MaMH CHAR(5) PRIMARY KEY NOT NULL,
    TenMH NVARCHAR(30) NOT NULL,
    SoTC INT NOT NULL
);

CREATE TABLE KETQUA (
    MaSV CHAR(5) NOT NULL,
    MaMH CHAR(5) NOT NULL,
    Diem REAL NOT NULL,
    PRIMARY KEY (MaSV, MaMH),
    FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV),
    FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH)
);
GO

INSERT INTO LOP VALUES ('S001', N'TMDT', 55, '2005-09-01');
INSERT INTO LOP VALUES ('S002', N'Công Nghệ Thông Tin', 50, '2005-09-01');
INSERT INTO LOP VALUES ('S003', N'Marketing', 45, '2005-09-01');
INSERT INTO SINHVIEN VALUES ('001', N'Nguyễn Thùy Trúc', '2005-09-13', 'S001');
INSERT INTO SINHVIEN VALUES ('002', N'Trần Đức Mạnh', '2005-05-24', 'S002');
INSERT INTO SINHVIEN VALUES ('003', N'Phạm Ánh Nguyệt', '2005-01-31', 'S003');
INSERT INTO MONHOC VALUES ('01', N'Cơ sở dữ liệu', 3);
INSERT INTO MONHOC VALUES ('02', N'Nhập môn lập trình', 3);
INSERT INTO MONHOC VALUES ('03', N'Tiếp thị số', 3);
INSERT INTO KETQUA VALUES ('001', '01', 8.5);
INSERT INTO KETQUA VALUES ('002', '02', 8.0);
INSERT INTO KETQUA VALUES ('003', '03', 9.0);
SELECT * FROM LOP;
SELECT * FROM SINHVIEN;
SELECT * FROM MONHOC;
SELECT * FROM KETQUA;

ALTER DATABASE QLSV MODIFY NAME = QLHS;
USE master;
GO
DROP DATABASE QLHS;
GO
