CREATE DATABASE QLBH	
ON PRIMARY
(NAME = QLBH_data1, FILENAME = 'D:\CSDL\QLBH_data1.mdf',
SIZE = 10MB, MAXSIZE= 40MB, FILEGROWTH = 1MB)
LOG ON
(NAME = QLBG_Log, FILENAME = 'D:\CSDL\QLBH.ndf',
SIZE = 6MB, MAXSIZE = 8MB, FILEGROWTH = 1MB)
EXEC sp_helpDb QLBH
EXEC sp_spaceused
EXEC sp_helpfile
ALTER DATABASE QLBH ADD FILEGROUP DuLieuQLBH
ALTER DATABASE QLBH ADD FILE
(NAME = QLBH_data2, FILENAME = 'D:\CSDL\QLBH_data2.ndf',
SIZE = 10MB, MAXSIZE = 40MB, FILEGROWTH = 1MB)
TO FILEGROUP DuLieuQLBH
EXEC sp_helpfilegroup
ALTER DATABASE QLBH Set Read_Only
EXEC sp_helpDB QLBH
ALTER DATABASE QLBH Set READ_WRITE
ALTER DATABASE QLBH MODIFY FILE (NAME = QLBH_data1, SIZE = 50MB)
ALTER DATABASE QLBH MODIFY FILE (NAME = QLNH_log, SIZE = 15MB)